version: "3"
services:
  db:
    image: "postgres"
    container_name: "my_postgres"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file:
      - .env
